apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-app
spec:
  replicas: 1
  # replicas: 1
  selector:
    matchLabels:
      app: basic-app # this is used by the selector ( here Deployment )
  template:
    metadata:
      labels: # this lables is for the below specified resources ( here Pod )
        app: basic-app
    spec:
      containers:
      - name: basic-app
        image: basic-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
