-- seed_data.sql
-- Creates example tables, inserts seed data, and provides a sample function/procedure.
SET ECHO ON
SET FEEDBACK ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

-- Ensure we operate in the PDB target
ALTER SESSION SET CONTAINER = dcs_core_local;
PROMPT Current Container set to dcs_core_local

-- Create tables in DCS schema using fully qualified names (idempotent patterns)
-- Departments table
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE DCS.DEPARTMENTS (
      DEPT_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
      NAME VARCHAR2(100) NOT NULL UNIQUE
    )
  ]';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE = -955 THEN
    NULL; -- table exists
  ELSE
    RAISE;
  END IF;
END;
/

-- Employees table
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE DCS.EMPLOYEES (
      EMP_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
      FIRST_NAME VARCHAR2(100),
      LAST_NAME VARCHAR2(100),
      DEPT_ID NUMBER,
      SALARY NUMBER(12,2),
      HIRE_DATE DATE DEFAULT SYSDATE,
      CONSTRAINT FK_EMP_DEPT FOREIGN KEY (DEPT_ID) REFERENCES DCS.DEPARTMENTS(DEPT_ID)
    )
  ]';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE = -955 THEN
    NULL;
  ELSE
    RAISE;
  END IF;
END;
/

-- Seed departments (idempotent: ignore duplicates)
BEGIN
  INSERT INTO DCS.DEPARTMENTS (NAME) VALUES ('Engineering');
  INSERT INTO DCS.DEPARTMENTS (NAME) VALUES ('HR');
  INSERT INTO DCS.DEPARTMENTS (NAME) VALUES ('Finance');
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE = -00001 THEN
    NULL; -- duplicate entry; ignore
  ELSE
    RAISE;
  END IF;
END;
/

-- Seed employees (attempt inserts; allow duplicates to be ignored if constraints change)
BEGIN
  INSERT INTO DCS.EMPLOYEES (FIRST_NAME, LAST_NAME, DEPT_ID, SALARY)
  VALUES ('Alice', 'Anderson', (SELECT DEPT_ID FROM DCS.DEPARTMENTS WHERE NAME='Engineering' AND ROWNUM=1), 120000);

  INSERT INTO DCS.EMPLOYEES (FIRST_NAME, LAST_NAME, DEPT_ID, SALARY)
  VALUES ('Bob', 'Brown', (SELECT DEPT_ID FROM DCS.DEPARTMENTS WHERE NAME='Engineering' AND ROWNUM=1), 110000);

  INSERT INTO DCS.EMPLOYEES (FIRST_NAME, LAST_NAME, DEPT_ID, SALARY)
  VALUES ('Carol', 'Clark', (SELECT DEPT_ID FROM DCS.DEPARTMENTS WHERE NAME='HR' AND ROWNUM=1), 90000);
EXCEPTION WHEN OTHERS THEN
  NULL; -- ignore insert errors for idempotency
END;
/

COMMIT;

-- Create a function to get total salary by department
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE OR REPLACE FUNCTION DCS.total_dept_salary(p_dept_id IN NUMBER) RETURN NUMBER IS
      v_sum NUMBER;
    BEGIN
      SELECT NVL(SUM(SALARY),0) INTO v_sum FROM DCS.EMPLOYEES WHERE DEPT_ID = p_dept_id;
      RETURN v_sum;
    END;
  ]';
EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('Function create error: ' || SQLERRM);
  RAISE;
END;
/

-- Create a procedure to grant raise by percent to an employee
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE OR REPLACE PROCEDURE DCS.give_raise(p_emp_id IN NUMBER, p_percent IN NUMBER) IS
    BEGIN
      UPDATE DCS.EMPLOYEES
      SET SALARY = NVL(SALARY,0) * (1 + NVL(p_percent,0)/100)
      WHERE EMP_ID = p_emp_id;
      COMMIT;
    END;
  ]';
EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('Procedure create error: ' || SQLERRM);
  RAISE;
END;
/

COMMIT;

PROMPT Seed data and objects created in DCS schema.